### ISSUE TITLE
好多都无法识别!!!

### ISSUE THREAD

**Issue by Linvas** [tuotoo/qrcode#8]
我想识别支付宝图片里面的二维码, 都无法识别, 只能用来识别只有二维码的情况, 带点边框就不行了

**Comment by zwj186** [comment]
是啊，很多二维码图片都不能识别出来，希望作者完善更多的二维码标准支持！

**Comment by Linvas** [comment]
> 是啊，很多二维码图片都不能识别出来，希望作者完善更多的二维码标准支持！

已经换了, 别用这个了

**Comment by zinwalin** [comment]
> > 是啊，很多二维码图片都不能识别出来，希望作者完善更多的二维码标准支持！
> 
> 已经换了, 别用这个了

有推荐的二维码识别库吗？
